# Generated by Django 4.1.3 on 2022-11-21 12:54

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dr_code', models.CharField(default=website.models.generate_random_code, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['dr_code'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(default=website.models.generate_random_code, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('dr_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctor')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_code', models.CharField(default=website.models.generate_random_code, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=12, null=True)),
                ('dr_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_number', models.CharField(default=website.models.generate_random_number, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pat_name', models.CharField(max_length=100, null=True)),
                ('diagnosis', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField()),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('other', models.CharField(max_length=1000, null=True)),
                ('pat_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.patient')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnosis',
                'ordering': ['diagnosis_number'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.CharField(default=website.models.generate_random_number, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pat_name', models.CharField(max_length=100, null=True)),
                ('dr_name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('dr_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctor')),
                ('pat_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.patient')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['bill_no'],
            },
        ),
    ]
